#!/bin/bash

# This is a RackTables gateway for changing switch ports membership
# across VLANs. It works accordingly to the gateway protocol described
# in gateways.php and accepts the following commands on its stdin:
# * listvlans: list all VLANs found on the switch, propably filtering
# out those administratively prohibited. Only the VLANs from this
# list will be allowed as new destination for 'set' command.
# * listports: list all ports on the switch and their current status.
# Untagged (switchport mode access) ports will be shown with their
# VLAN ID and tagged ports will be shown as 'trunk' regardless of
# how many VLANs they are members of.

usage()
{
	echo "Usage: $0 <endpoint> <hwtype> <swtype> <username>"
	exit 1;
}

[ $# = 4 ] || usage

while read cmd arg1 arg2; do
	case $cmd in
		listvlans)
			echo 'OK!200,204,203,202,201,205,333,334'
			;;
		listports)
			echo -n 'OK!fa0/0/1=200,fa0/0/2=205,fa0/0/3=202,fa0/0/4=trunk,fa0/0/5=333,fa0/0/6=334,fa0/0/7=333,fa0/0/8=334,'
			echo -n 'fa0/0/9=200,fa0/0/10=205,fa0/0/11=202,fa0/0/12=trunk,fa0/0/13=333,fa0/0/14=334,fa0/0/15=333,fa0/0/16=334,'
			echo -n 'fa0/1/1=200,fa0/1/2=205,fa0/1/3=202,fa0/1/4=trunk,fa0/1/5=333,fa0/1/6=334,fa0/1/7=333,fa0/1/8=334,'
			echo 'fa0/1/9=200,fa0/1/10=205,fa0/1/11=202,fa0/1/12=trunk,fa0/1/13=333,fa0/1/14=334,fa0/1/15=333,fa0/1/16=334'
			;;
		set)
			echo 'OK!'
			;;
		*)
			echo "ERR!unknown command $cmd"
	esac
done

exit 0
