FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update && apt-get install mariadb-server -y

COPY . /app

RUN printf "[mysqld]\ncharacter-set-server=utf8\n" > /etc/mysql/conf.d/charset.cnf

# RUN chown www-data:nogroup -R /app/wwwroot && chmod -R 0700 /app/wwwroot && chmod a=rw /app/wwwroot/inc/secret.php

EXPOSE 3306

ENTRYPOINT ["/app/tests/ci_setup_mysql.sh" "racktables_db" "racktables" "$(dd if=/dev/random bs=16 count=1 status=none | od -A n -t x | tr -d ' ')"]

CMD mysql_safe