LOCK TABLES `Dictionary` WRITE;
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,1,'noname/unknown');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,65,'Cisco Catalyst Express 500G-12TC');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,3,'IBM xSeries 305');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,4,'IBM xSeries 306');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,5,'IBM xSeries 306m');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,6,'IBM xSeries 326m');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,7,'IBM xSeries 330');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,8,'IBM xSeries 335');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,9,'Sun Ultra 10');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,10,'Sun Enterprise 420R');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,11,'Sun Fire X2100');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,12,'Sun Fire E4900');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,13,'Sun Netra X1');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,14,'IBM xSeries 346');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,15,'Dell PowerEdge 1650');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,16,'Dell PowerEdge 2850');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,11,'Foundry FastIron WorkGroup');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,1,'noname/unknown');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,13,'Foundry FastIron II');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,14,'Foundry ServerIron');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,15,'Foundry ServerIron XL');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,16,'Foundry ServerIron 350');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,17,'Foundry FastIron Edge 2402');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,18,'Foundry FastIron Edge 4802');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,19,'Foundry FastIron Edge X424');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,20,'Cisco Catalyst 2924XL');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,14,'RHEL1');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,17,'RHEL4');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,32,'Foundry FastIron Edge 2402-PREM');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,34,'Foundry FastIron GS 624P-POE');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,16,'RHEL3');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,1,'RHFC1');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,2,'RHFC2');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,3,'RHFC3');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,4,'RHFC4');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,5,'RHFC5');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,6,'RHFC6');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (14,1,'Cisco IOS 12.0');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (19,6,'Dell PowerVault ML6000');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (19,3,'Sun StorageTek L1400');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,44,'Cisco Catalyst 2960-48TC');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (14,2,'Foundry SLB');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,31,'Foundry NetIron XMR 4000');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,30,'Foundry NetIron MLX-32');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,28,'Foundry NetIron MLX-8');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,13,'Windows Vista');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,12,'Windows 2003');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,29,'Foundry NetIron MLX-16');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,32,'Foundry NetIron XMR 8000');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,26,'Foundry FastIron SuperX');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (16,1,'Cisco IOS 12.0');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (16,2,'Cisco IOS 12.1');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (16,3,'Cisco IOS 12.2');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (16,4,'Cisco IOS 12.3');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (16,5,'Cisco IOS 12.4');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (19,5,'Sun StorageTek C4');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (19,4,'Sun StorageTek SL8500');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,7,'Solaris 8');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,8,'Solaris 9');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,9,'Solaris 10');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,1,'Foundry BigIron 4000');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,2,'Cisco 7609');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,3,'Cisco 2610XM');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,4,'Cisco 2611XM');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,5,'Cisco 3620');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,6,'Cisco 3640');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,45,'Cisco Catalyst 3560-E');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (14,9,'Foundry WXM');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,43,'Cisco Catalyst 3560-8PC');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,17,'Sun Fire V210');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,18,'Sun Fire V240');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,33,'Foundry FastIron GS 624P');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (18,1,'Sun StorEdge A1000');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,19,'IBM xSeries 326');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,64,'Cisco Catalyst Express 500-24TT');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (18,7,'Sun StorageTek 6140');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,21,'Sun Netra t1 105');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,22,'Sun Enterprise 4500');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (16,6,'Foundry L3');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (14,11,'Foundry L2');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (19,1,'Dell PowerVault 136T');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (18,3,'Dell/EMC AX150');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (18,4,'EMC CLARiiON CX600');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (19,9,'Dell PowerVault TL2000');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (18,5,'Sun StorEdge D240');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,27,'Foundry NetIron MLX-4');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,11,'Windows XP');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,10,'Windows 2000');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (14,13,'Foundry full L3');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (19,11,'Sun StorageTek C2');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (14,15,'Foundry basic L3');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,15,'RHEL2');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,63,'Cisco Catalyst Express 500-24PC');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,24,'Dell PowerEdge 1950');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (19,2,'Sun StorageTek SL500');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,7,'Cisco 2621XM');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,8,'Cisco 7206VXR');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,9,'Cisco 2651XM');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,10,'Cisco 7204VXR');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,11,'Cisco 2612');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,12,'Cisco 2620XM');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,13,'Cisco 2650XM');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,14,'Cisco 2691');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,15,'Cisco 7603');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,16,'Cisco 7606');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,17,'Cisco 7613');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,18,'Cisco 2801');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,19,'Cisco 2811');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,20,'Cisco 2821');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,21,'Cisco 2851');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,22,'Cisco 3725');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,23,'Cisco 3745');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,24,'Cisco 3825');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,25,'Cisco 3845');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,26,'Netscreen 100');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,29,'Cisco Catalyst 2912XL');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (19,10,'Dell PowerVault 124T');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,25,'Dell PowerEdge 1550');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,26,'Sun Ultra 5');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,27,'Dell PowerEdge 2950');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (14,19,'Cisco IOS 11.2');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (18,6,'EMC CLARiiON CX300');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,28,'Dell PowerEdge 650');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,29,'Dell PowerEdge 4600');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,31,'Foundry FastIron GS 648P');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (19,8,'Dell PowerVault TL4000');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (19,7,'Dell PowerVault 132T');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,33,'Foundry NetIron XMR 16000');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,34,'Foundry NetIron XMR 32000');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,35,'Foundry BigIron RX-4');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,36,'Foundry BigIron RX-8');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,37,'Foundry BigIron RX-16');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,35,'Foundry FastIron GS 648P-POE');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,36,'Foundry ServerIron 4G');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,37,'Foundry ServerIron 4G-SSL');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,38,'Foundry FastIron Edge X448');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,39,'Foundry FastIron Edge X424HF');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,40,'Foundry FastIron Edge X424-POE');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,41,'Foundry FastIron SX 800');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,42,'Foundry FastIron SX 1600');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,46,'Cisco Catalyst Express 500-24LC');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,47,'Cisco Catalyst 3750-24TS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,48,'Cisco Catalyst 3750-E');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,49,'Cisco Catalyst 4503');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,50,'Cisco Catalyst 6513');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,51,'Cisco Catalyst 4948');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,52,'Cisco Catalyst 6509-E');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,53,'Cisco Catalyst 6509-NEB-A');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,54,'Cisco Catalyst 6506-E');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,55,'Cisco Catalyst 6504-E');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,56,'Cisco Catalyst 6503-E');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,57,'Cisco Catalyst 6503');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,58,'Cisco Catalyst 6506');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,59,'Cisco Catalyst 6509-NEB');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,60,'Cisco Catalyst 4506');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,61,'Cisco Catalyst 4507R');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,62,'Cisco Catalyst 4510R');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,18,'ALTLinux Master 2.0');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,19,'ALTLinux Master 2.2');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,20,'ALTLinux Master 2.4');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,21,'RHFC7');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,66,'Cisco Catalyst 2960-48TT');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,67,'Cisco Catalyst 2960-24TC');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,68,'Cisco Catalyst 2960-24TT');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,69,'Cisco Catalyst 2960-8TC');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,70,'Cisco Catalyst 2960G-48TC');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,71,'Cisco Catalyst 2960G-24TC');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,72,'Cisco Catalyst 2960G-8TC');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,73,'Cisco Catalyst 3560-24TS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,74,'Cisco Catalyst 3560-48TS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,75,'Cisco Catalyst 3560-24PS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,76,'Cisco Catalyst 3560-48PS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,77,'Cisco Catalyst 3560G-24TS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,78,'Cisco Catalyst 3560G-48TS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,79,'Cisco Catalyst 3560G-24PS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,80,'Cisco Catalyst 3560G-48PS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,81,'Cisco Catalyst 3750-48TS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,82,'Cisco Catalyst 3750-24PS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,83,'Cisco Catalyst 3750-48PS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,84,'Cisco Catalyst 3750-24FS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,85,'Cisco Catalyst 3750G-24T');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,86,'Cisco Catalyst 3750G-24TS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,87,'Cisco Catalyst 3750G-24TS-1U');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,88,'Cisco Catalyst 3750G-48TS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,89,'Cisco Catalyst 3750G-24PS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,90,'Cisco Catalyst 3750G-48PS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,91,'Cisco Catalyst 3750G-16TD');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,92,'Cisco Catalyst 3750G-12S');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,93,'Cisco Catalyst 3750G-24WS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,38,'Cisco 1841');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,39,'Cisco 1812');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,40,'Cisco 1811');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,41,'Cisco 1803');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,42,'Cisco 1802');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,43,'Cisco 1801');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,44,'Cisco 7202');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,45,'Cisco 7204');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,46,'Cisco 7206');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,47,'Cisco 7604');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,48,'Cisco OSR-7609');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (14,20,'Cisco IOS 12.1');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (14,21,'Cisco IOS 12.2');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (14,22,'Cisco IOS 11.3');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (16,7,'Cisco IOS 11.2');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (16,8,'Cisco IOS 11.3');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (18,8,'Sun StorageTek 3511');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (18,9,'Sun StorageTek 3510');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (18,10,'Sun StorageTek 3320');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (18,11,'Sun StorageTek 3120');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,30,'IBM xSeries 3250');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,31,'IBM xSeries 3455');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,32,'IBM xSeries 3550');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,33,'IBM xSeries 3650');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,34,'IBM xSeries 3655');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,35,'IBM xSeries 3650 T');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,36,'IBM xSeries 3755');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,37,'IBM xSeries 3850');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,38,'Sun Fire X4600');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,39,'Sun Fire X4500');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,40,'Sun Fire X4200');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,41,'Sun Fire X4100');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,42,'Sun Fire X2100 M2');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,43,'Sun Fire X2200 M2');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,44,'Sun Fire V40z');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,45,'Sun Fire V125');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,46,'Sun Fire V215');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,47,'Sun Fire V245');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,48,'Sun Fire V445');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,49,'Sun Fire V440');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,50,'Sun Fire V490');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,51,'Sun Fire V890');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,52,'Sun Fire E2900');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,53,'Sun Fire V1280');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,54,'IBM pSeries 185');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,55,'IBM pSeries 505');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,56,'IBM pSeries 505Q');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,57,'IBM pSeries 510');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,58,'IBM pSeries 510Q');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,59,'IBM pSeries 520');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,60,'IBM pSeries 520Q');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,61,'IBM pSeries 550');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,62,'IBM pSeries 550Q');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,63,'HP ProLiant DL140');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,64,'HP ProLiant DL145');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,65,'HP ProLiant DL320');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,66,'HP ProLiant DL360');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,67,'HP ProLiant DL380');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,68,'HP ProLiant DL385');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,69,'HP ProLiant DL580');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,70,'HP ProLiant DL585');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,71,'HP ProLiant ML110');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,72,'HP ProLiant ML150');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,73,'HP ProLiant ML310');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,74,'HP ProLiant ML350');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,75,'HP ProLiant ML370');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,76,'HP ProLiant ML570');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (18,12,'Dell PowerVault NX1950');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (18,13,'Dell PowerVault 220S');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (18,14,'Dell PowerVault MD3000');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,22,'SLES10');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,23,'Debian 3.0');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,24,'Debian 3.1');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,49,'Foundry BigIron 8000');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,50,'Foundry BigIron 16000');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,94,'Foundry EdgeIron 2402CF');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,95,'Foundry EdgeIron 24G');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,96,'Foundry EdgeIron 4802CF');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,97,'Foundry EdgeIron 48G');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,98,'Foundry EdgeIron 24GS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,99,'Foundry EdgeIron 48GS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,100,'Foundry EdgeIron 8X10G');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,101,'Foundry FastIron Edge 4802-PREM');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,102,'Foundry FastIron Edge 12GCF');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,103,'Foundry FastIron Edge 12GCF-PREM');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,104,'Foundry FastIron Edge 9604');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,105,'Foundry FastIron Edge 9604-PREM');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,106,'Foundry FastIron Edge 2402-POE');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,107,'Foundry FastIron Edge 4802-POE');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,108,'Foundry FastIron Workgroup X424');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,109,'Foundry FastIron Workgroup X448');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,110,'Foundry ServerIron 450');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,111,'Foundry ServerIron 850');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,112,'Foundry ServerIron GT C');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,113,'Foundry ServerIron GT E');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,25,'FreeBSD 1.x');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,26,'FreeBSD 2.x');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,27,'FreeBSD 3.x');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,28,'FreeBSD 4.x');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,29,'FreeBSD 5.x');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,30,'FreeBSD 6.x');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,31,'RHFC8');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,32,'ALTLinux Master 4.0');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,114,'Cisco Catalyst 2970G-24T');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,115,'Cisco Catalyst 2970G-24TS');
UNLOCK TABLES;
