LOCK TABLES `Dictionary` WRITE;
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,42,'noname/unknown');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,43,'IBM xSeries 305');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,44,'IBM xSeries 306');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,45,'IBM xSeries 306m');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,46,'IBM xSeries 326m');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,47,'IBM xSeries 330');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,48,'IBM xSeries 335');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,49,'Sun Ultra 10');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,50,'Sun Enterprise 420R');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,51,'Sun Fire X2100');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,52,'Sun Fire E4900');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,53,'Sun Netra X1');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,54,'IBM xSeries 346');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,55,'Dell PowerEdge 1650');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,56,'Dell PowerEdge 2850');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,57,'Sun Fire V210');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,58,'Sun Fire V240');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,59,'IBM xSeries 326');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,60,'Sun Netra t1 105');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,61,'Sun Enterprise 4500');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,62,'Dell PowerEdge 1950');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,63,'Dell PowerEdge 1550');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,64,'Sun Ultra 5');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,65,'Dell PowerEdge 2950');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,66,'Dell PowerEdge 650');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,67,'Dell PowerEdge 4600');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,68,'IBM xSeries 3250');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,69,'IBM xSeries 3455');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,70,'IBM xSeries 3550');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,71,'IBM xSeries 3650');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,72,'IBM xSeries 3655');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,73,'IBM xSeries 3650 T');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,74,'IBM xSeries 3755');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,75,'IBM xSeries 3850');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,76,'Sun Fire X4600');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,77,'Sun Fire X4500');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,78,'Sun Fire X4200');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,79,'Sun Fire X4100');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,80,'Sun Fire X2100 M2');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,81,'Sun Fire X2200 M2');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,82,'Sun Fire V40z');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,83,'Sun Fire V125');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,84,'Sun Fire V215');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,85,'Sun Fire V245');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,86,'Sun Fire V445');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,87,'Sun Fire V440');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,88,'Sun Fire V490');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,89,'Sun Fire V890');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,90,'Sun Fire E2900');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,91,'Sun Fire V1280');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,92,'IBM pSeries 185');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,93,'IBM pSeries 505');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,94,'IBM pSeries 505Q');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,95,'IBM pSeries 510');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,96,'IBM pSeries 510Q');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,97,'IBM pSeries 520');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,98,'IBM pSeries 520Q');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,99,'IBM pSeries 550');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,100,'IBM pSeries 550Q');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,101,'HP ProLiant DL140');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,102,'HP ProLiant DL145');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,103,'HP ProLiant DL320');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,104,'HP ProLiant DL360');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,105,'HP ProLiant DL380');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,106,'HP ProLiant DL385');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,107,'HP ProLiant DL580');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,108,'HP ProLiant DL585');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,109,'HP ProLiant ML110');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,110,'HP ProLiant ML150');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,111,'HP ProLiant ML310');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,112,'HP ProLiant ML350');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,113,'HP ProLiant ML370');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,114,'HP ProLiant ML570');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,115,'noname/unknown');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,116,'Foundry FastIron WorkGroup');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,117,'Foundry FastIron II');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,118,'Foundry ServerIron');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,119,'Foundry ServerIron XL');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,120,'Foundry ServerIron 350');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,121,'Foundry FastIron Edge 2402');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,122,'Foundry FastIron Edge 4802');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,123,'Foundry FastIron Edge X424');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,124,'Cisco Catalyst 2924XL');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,125,'Foundry FastIron SuperX');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,126,'Cisco Catalyst 2912XL');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,127,'Foundry FastIron GS 648P');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,128,'Foundry FastIron Edge 2402-PREM');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,129,'Foundry FastIron GS 624P');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,130,'Foundry FastIron GS 624P-POE');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,131,'Foundry FastIron GS 648P-POE');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,132,'Foundry ServerIron 4G');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,133,'Foundry ServerIron 4G-SSL');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,134,'Foundry FastIron Edge X448');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,135,'Foundry FastIron Edge X424HF');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,136,'Foundry FastIron Edge X424-POE');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,137,'Foundry FastIron SX 800');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,138,'Foundry FastIron SX 1600');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,139,'Cisco Catalyst 3560-8PC');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,140,'Cisco Catalyst 2960-48TC');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,141,'Cisco Catalyst 3560-E');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,142,'Cisco Catalyst Express 500-24LC');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,143,'Cisco Catalyst 3750-24TS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,144,'Cisco Catalyst 3750-E');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,145,'Cisco Catalyst 4503');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,146,'Cisco Catalyst 6513');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,147,'Cisco Catalyst 4948');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,148,'Cisco Catalyst 6509-E');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,149,'Cisco Catalyst 6509-NEB-A');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,150,'Cisco Catalyst 6506-E');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,151,'Cisco Catalyst 6504-E');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,152,'Cisco Catalyst 6503-E');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,153,'Cisco Catalyst 6503');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,154,'Cisco Catalyst 6506');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,155,'Cisco Catalyst 6509-NEB');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,156,'Cisco Catalyst 4506');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,157,'Cisco Catalyst 4507R');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,158,'Cisco Catalyst 4510R');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,159,'Cisco Catalyst Express 500-24PC');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,160,'Cisco Catalyst Express 500-24TT');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,161,'Cisco Catalyst Express 500G-12TC');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,162,'Cisco Catalyst 2960-48TT');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,163,'Cisco Catalyst 2960-24TC');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,164,'Cisco Catalyst 2960-24TT');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,165,'Cisco Catalyst 2960-8TC');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,166,'Cisco Catalyst 2960G-48TC');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,167,'Cisco Catalyst 2960G-24TC');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,168,'Cisco Catalyst 2960G-8TC');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,169,'Cisco Catalyst 3560-24TS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,170,'Cisco Catalyst 3560-48TS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,171,'Cisco Catalyst 3560-24PS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,172,'Cisco Catalyst 3560-48PS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,173,'Cisco Catalyst 3560G-24TS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,174,'Cisco Catalyst 3560G-48TS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,175,'Cisco Catalyst 3560G-24PS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,176,'Cisco Catalyst 3560G-48PS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,177,'Cisco Catalyst 3750-48TS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,178,'Cisco Catalyst 3750-24PS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,179,'Cisco Catalyst 3750-48PS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,180,'Cisco Catalyst 3750-24FS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,181,'Cisco Catalyst 3750G-24T');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,182,'Cisco Catalyst 3750G-24TS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,183,'Cisco Catalyst 3750G-24TS-1U');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,184,'Cisco Catalyst 3750G-48TS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,185,'Cisco Catalyst 3750G-24PS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,186,'Cisco Catalyst 3750G-48PS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,187,'Cisco Catalyst 3750G-16TD');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,188,'Cisco Catalyst 3750G-12S');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,189,'Cisco Catalyst 3750G-24WS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,190,'Foundry EdgeIron 2402CF');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,191,'Foundry EdgeIron 24G');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,192,'Foundry EdgeIron 4802CF');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,193,'Foundry EdgeIron 48G');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,194,'Foundry EdgeIron 24GS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,195,'Foundry EdgeIron 48GS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,196,'Foundry EdgeIron 8X10G');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,197,'Foundry FastIron Edge 4802-PREM');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,198,'Foundry FastIron Edge 12GCF');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,199,'Foundry FastIron Edge 12GCF-PREM');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,200,'Foundry FastIron Edge 9604');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,201,'Foundry FastIron Edge 9604-PREM');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,202,'Foundry FastIron Edge 2402-POE');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,203,'Foundry FastIron Edge 4802-POE');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,204,'Foundry FastIron Workgroup X424');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,205,'Foundry FastIron Workgroup X448');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,206,'Foundry ServerIron 450');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,207,'Foundry ServerIron 850');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,208,'Foundry ServerIron GT C');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,209,'Foundry ServerIron GT E');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,210,'Cisco Catalyst 2970G-24T');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,211,'Cisco Catalyst 2970G-24TS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,212,'RHFC1');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,213,'RHFC2');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,214,'RHFC3');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,215,'RHFC4');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,216,'RHFC5');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,217,'RHFC6');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,218,'Solaris 8');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,219,'Solaris 9');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,220,'Solaris 10');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,221,'Windows 2000');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,222,'Windows XP');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,223,'Windows 2003');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,224,'Windows Vista');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,225,'RHEL1');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,226,'RHEL2');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,227,'RHEL3');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,228,'RHEL4');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,229,'ALTLinux Master 2.0');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,230,'ALTLinux Master 2.2');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,231,'ALTLinux Master 2.4');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,232,'RHF7');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,233,'SLES10');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,234,'Debian 3.0 (woody)');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,235,'Debian 3.1 (sarge)');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,236,'FreeBSD 1.x');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,237,'FreeBSD 2.x');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,238,'FreeBSD 3.x');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,239,'FreeBSD 4.x');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,240,'FreeBSD 5.x');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,241,'FreeBSD 6.x');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,242,'RHF8');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,243,'ALTLinux Master 4.0');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (14,244,'Cisco IOS 12.0');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (14,245,'Foundry SLB');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (14,246,'Foundry WXM');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (14,247,'Foundry L2');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (14,248,'Foundry full L3');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (14,249,'Foundry basic L3');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (14,250,'Cisco IOS 11.2');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (14,251,'Cisco IOS 12.1');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (14,252,'Cisco IOS 12.2');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (14,253,'Cisco IOS 11.3');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (16,254,'Cisco IOS 12.0');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (16,255,'Cisco IOS 12.1');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (16,256,'Cisco IOS 12.2');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (16,257,'Cisco IOS 12.3');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (16,258,'Cisco IOS 12.4');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (16,259,'Foundry L3');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (16,260,'Cisco IOS 11.2');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (16,261,'Cisco IOS 11.3');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,262,'Foundry BigIron 4000');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,263,'Cisco 7609');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,264,'Cisco 2610XM');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,265,'Cisco 2611XM');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,266,'Cisco 3620');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,267,'Cisco 3640');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,268,'Cisco 2621XM');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,269,'Cisco 7206VXR');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,270,'Cisco 2651XM');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,271,'Cisco 7204VXR');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,272,'Cisco 2612');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,273,'Cisco 2620XM');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,274,'Cisco 2650XM');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,275,'Cisco 2691');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,276,'Cisco 7603');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,277,'Cisco 7606');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,278,'Cisco 7613');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,279,'Cisco 2801');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,280,'Cisco 2811');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,281,'Cisco 2821');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,282,'Cisco 2851');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,283,'Cisco 3725');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,284,'Cisco 3745');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,285,'Cisco 3825');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,286,'Cisco 3845');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,287,'Netscreen 100');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,288,'Foundry NetIron MLX-4');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,289,'Foundry NetIron MLX-8');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,290,'Foundry NetIron MLX-16');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,291,'Foundry NetIron MLX-32');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,292,'Foundry NetIron XMR 4000');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,293,'Foundry NetIron XMR 8000');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,294,'Foundry NetIron XMR 16000');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,295,'Foundry NetIron XMR 32000');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,296,'Foundry BigIron RX-4');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,297,'Foundry BigIron RX-8');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,298,'Foundry BigIron RX-16');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,299,'Cisco 1841');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,300,'Cisco 1812');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,301,'Cisco 1811');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,302,'Cisco 1803');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,303,'Cisco 1802');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,304,'Cisco 1801');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,305,'Cisco 7202');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,306,'Cisco 7204');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,307,'Cisco 7206');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,308,'Cisco 7604');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,309,'Cisco OSR-7609');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,310,'Foundry BigIron 8000');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,311,'Foundry BigIron 15000');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (18,312,'Sun StorEdge A1000');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (18,313,'Dell/EMC AX150');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (18,314,'EMC CLARiiON CX600');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (18,315,'Sun StorEdge D240');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (18,316,'EMC CLARiiON CX300');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (18,317,'Sun StorageTek 6140');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (18,318,'Sun StorageTek 3511');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (18,319,'Sun StorageTek 3510');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (18,320,'Sun StorageTek 3320');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (18,321,'Sun StorageTek 3120');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (18,322,'Dell PowerVault NX1950');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (18,323,'Dell PowerVault 220S');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (18,324,'Dell PowerVault MD3000');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (19,325,'Dell PowerVault 136T');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (19,326,'Sun StorageTek SL500');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (19,327,'Sun StorageTek L1400');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (19,328,'Sun StorageTek SL8500');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (19,329,'Sun StorageTek C4');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (19,330,'Dell PowerVault ML6000');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (19,331,'Dell PowerVault 132T');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (19,332,'Dell PowerVault TL4000');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (19,333,'Dell PowerVault TL2000');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (19,334,'Dell PowerVault 124T');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (19,335,'Sun StorageTek C2');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,338,'Dell PowerConnect 2216');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,339,'Dell PowerConnect 2224');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,340,'Dell PowerConnect 2324');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,341,'Dell PowerConnect 2708');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,342,'Dell PowerConnect 2716');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,343,'Dell PowerConnect 2724');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,344,'Dell PowerConnect 2748');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,345,'Dell PowerConnect 3424');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,346,'Dell PowerConnect 3424P');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,347,'Dell PowerConnect 3448');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,348,'Dell PowerConnect 3448P');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,349,'Dell PowerConnect 5324');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,350,'Dell PowerConnect 6224');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,351,'Dell PowerConnect 6224P');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,352,'Dell PowerConnect 6224F');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,353,'Dell PowerConnect 6248');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,354,'Dell PowerConnect 6248P');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,355,'Dell PowerEdge 6850');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,356,'Dell PowerEdge 6950');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,357,'Dell PowerEdge R900');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,358,'Dell PowerEdge 4400');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,359,'Dell PowerEdge 2650');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,360,'Dell PowerEdge 2550');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,361,'Dell PowerEdge 750');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,362,'Dell PowerEdge 2450');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,363,'Dell PowerEdge 850');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,364,'Dell PowerEdge 1850');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,365,'Dell PowerEdge 860');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,366,'Dell PowerEdge 2900');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,367,'Dell PowerEdge 2970');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (11,368,'Dell PowerEdge SC1435');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,369,'Cisco Catalyst 6509');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,370,'Cisco ME 6524GS-8S');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,371,'Cisco ME 6524GT-8S');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,372,'Cisco Catalyst 4503-E');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,373,'Cisco Catalyst 4506-E');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,374,'Cisco Catalyst 4507R-E');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,375,'Cisco Catalyst 4510R-E');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,376,'Cisco Catalyst 3750-24TE-M');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,377,'Cisco Catalyst 4948-10GE');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,378,'Cisco ME 4924-10GE');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,379,'Cisco Catalyst 2960-24');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,380,'Cisco Catalyst 2950-24');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,381,'Cisco Catalyst 2950-12');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,382,'Cisco Catalyst 2950C-24');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,383,'Cisco Catalyst 2950G-24-DC');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,384,'Cisco Catalyst 2950SX-48');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,385,'Cisco Catalyst 2950SX-24');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,386,'Cisco Catalyst 2950T-24');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,387,'Cisco Catalyst 2950T-48');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,388,'Cisco Catalyst 2950G-12');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,389,'Cisco Catalyst 2950G-24');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,390,'Cisco Catalyst 2950G-48');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,391,'Cisco Catalyst 3508G XL');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,392,'Cisco Catalyst 3512 XL');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,393,'Cisco Catalyst 3524 XL');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,394,'Cisco Catalyst 3524 PWR XL');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,395,'Cisco Catalyst 3548 XL');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,396,'Cisco ME 2400-24TS-A');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,397,'Cisco ME 2400-24TS-D');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,398,'Cisco Catalyst 3550-12T');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,399,'Cisco Catalyst 3550-12G');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,400,'Cisco Catalyst 3550-24');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,401,'Cisco Catalyst 3550-24 FX');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,402,'Cisco Catalyst 3550-24 DC');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,403,'Cisco Catalyst 3550-24 PWR');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,404,'Cisco Catalyst 3550-48');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,405,'Cisco ME 3400G-12CS-A');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,406,'Cisco ME 3400G-12CS-D');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,407,'Cisco ME 3400G-2CS-A');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,408,'Cisco ME 3400-24TS-A');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,409,'Cisco ME 3400-24TS-D');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,410,'Cisco ME 3400-24FS-A');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,411,'Foundry FastIron GS 624XGP');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,412,'Foundry FastIron GS 624XGP-POE');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,413,'Foundry FastIron LS 624');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,414,'Foundry FastIron LS 648');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,415,'Foundry NetIron M2404F');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (12,416,'Foundry NetIron M2404C');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (17,417,'Foundry BigIron RX-32');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,418,'Debian 2.0 (hamm)');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,419,'Debian 2.1 (slink)');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,420,'Debian 2.2 (potato)');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,421,'Debian 4.0 (etch)');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,422,'ALTLinux Server 4.0');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,423,'ALTLinux Sisyphus');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,424,'openSUSE 10.0');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,425,'openSUSE 10.1');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,426,'openSUSE 10.2');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,427,'openSUSE 10.3');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,428,'Ubuntu 4.10');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,429,'Ubuntu 5.04');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,430,'Ubuntu 5.10');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,431,'Ubuntu 6.06 LTS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,432,'Ubuntu 6.10');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,433,'Ubuntu 7.04');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,434,'Ubuntu 7.10');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,435,'Ubuntu 8.04 LTS');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,436,'RHEL5');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (18,437,'Dell PowerVault 210S');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (18,438,'Dell PowerVault 221S');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,441,'CentOS-2');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,442,'CentOS-3');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,443,'CentOS-4');
INSERT INTO `Dictionary` (`chapter_no`, `dict_key`, `dict_value`) VALUES (13,444,'CentOS-5');
UNLOCK TABLES;
